# You can add more sources here and libraries if needed
SRCS += $(SRCS_PATH)drivers/$(MCU)/pwm.c
INCLUDES +=
LIBS +=
LDFLAGS +=

# Example:
# SRCS += $(SRCS_PATH)my_driver.c
# LIBS += my_lib.a
# include math.h lib
# LDFLAGS += -lm
