# You can add more sources here if needed
SRCS += $(SRCS_PATH)drivers/$(MCU)/pwm.c

# Define default network settings
CFLAGS += -DNETWORK_ADDRESS=$(default_network_address)
CFLAGS += -DNETWORK_CHANNEL=$(default_network_channel)
