# You can add more sources here if needed
# Use the same external flash driver in Thingy9161 as with nRF9161-DK
SRCS += board/pca10153/bootloader/external_flash_gd25lb256e.c

INCLUDES += -Imcu/nrf/common/vendor/hal
INCLUDES += -Ibootloader
