# You can add more sources here if needed
SRCS +=
INCLUDES +=

# Define default network settings
CFLAGS += -DNETWORK_ADDRESS=$(default_network_address)
CFLAGS += -DNETWORK_CHANNEL=$(default_network_channel)

# Enable CBOR library
TINY_CBOR=yes

# Enable application debug prints
APP_PRINTING=yes
