# You can add more sources here and libraries if needed
SRCS +=
INCLUDES +=
LIBS +=
LDFLAGS +=

SHARED_APP_CONFIG=yes
SHARED_APP_CONFIG_FILTERS=2

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes
