# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=1

SHARED_APP_CONFIG=yes
SHARED_APP_CONFIG_FILTERS=3

# Use Shared Data
SHARED_DATA=yes

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes
