# This application use HAL for buttons and leds
HAL_BUTTON=yes
HAL_LED=yes

# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=4

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes
