# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=1

# Enable Local Provisioning library
LOCAL_PROVISIONING=yes
STACK_STATE_LIB=yes

# HAL button functions
HAL_BUTTON=yes

# HAL led functions
HAL_LED=yes

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes
