# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=1

#Use Shared data
SHARED_DATA=yes

# This application use HAL for buttons and leds
HAL_BUTTON=yes
HAL_LED=yes

# Enabled shared Shutdown library
STACK_STATE_LIB=yes
STACK_STATE_CBS=1
