# Custom logs to have High precision time
CFLAGS += -DDEBUG_LOG_CUSTOM
CFLAGS += -DDEBUG_LOG_PRINT_MODULE_NAME
CFLAGS += -DDEBUG_LOG_PRINT_TIME_HP
CFLAGS += -DDEBUG_LOG_PRINT_LEVEL

# Enable software AES
SW_AES=yes

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes