# You can add more sources here and libraries if needed
SRCS +=
INCLUDES +=
LIBS +=
LDFLAGS +=

# Example:
# SRCS += $(SRCS_PATH)my_driver.c
# LIBS += my_lib.a
# include math.h lib
# LDFLAGS += -lm

# Custom logs to have High precision time
CFLAGS += -DDEBUG_LOG_CUSTOM
CFLAGS += -DDEBUG_LOG_PRINT_MODULE_NAME
CFLAGS += -DDEBUG_LOG_PRINT_TIME_HP
CFLAGS += -DDEBUG_LOG_PRINT_LEVEL

# Enable software AES
SW_AES=yes

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes