# You can add more sources here if needed
SRCS +=
INCLUDES +=

# Define default network settings
CFLAGS += -DNETWORK_ADDRESS=$(default_network_address)
CFLAGS += -DNETWORK_CHANNEL=$(default_network_channel)

# Enable application debug prints
APP_PRINTING=yes

# Use Shared LibData
SHARED_LIBDATA=yes

# Generic util functions are needed (api.c)
include $(UTIL_PATH)makefile
