# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=1

# This enables the debug logs in the application. This has no effect on board without a
# serial port; compiled code is just not linked.
APP_PRINTING=yes
