# You can add more sources here and libraries if needed
SRCS +=
INCLUDES +=
LIBS +=
LDFLAGS +=

# Example:
# SRCS += $(SRCS_PATH)my_driver.c
# LIBS += my_lib.a
# include math.h lib
# LDFLAGS += -lm

# This enables the debug logs in the application. This has no effect on board without a
# serial port; compiled code is just not linked.
APP_PRINTING=yes
