# Enable App time synchro (needed by app)
RTC=yes
RTC_CBS=1

# Enable shared data library (needed by control library)
SHARED_DATA=yes

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes

# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=1
