# Enable shared data library (needed by provisioning proxy library)
SHARED_DATA=yes

# Enable CBOR library (needed by provisioning proxy library)
TINY_CBOR=yes

# Enable software AES (needed by provisioning proxy library)
SW_AES=yes

# Enable Provisioning Proxy library
PROVISIONING_PROXY=yes

# HAL button functions
HAL_BUTTON=yes

# Enable the debug logs (has no effect on board without serial port)
APP_PRINTING=yes
