ifneq ($(default_operating_mode),0)
    CFLAGS+= -DENABLE_LOW_LATENCY_MODE
endif

# Use Shared Data
SHARED_DATA=yes

# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=1

APP_PRINTING=yes
# This application use HAL for buttons and leds
HAL_BUTTON=yes
HAL_LED=yes