SRCS += bootloader_test/tests/test_memory_areas.c
SRCS += bootloader_test/tests/test_info.c
SRCS += bootloader_test/tests/test_timings.c
SRCS += bootloader_test/main.c
SRCS += bootloader_test/print/print.c
SRCS += bootloader_test/print/syscalls.c
SRCS += bootloader_test/drivers/$(MCU)/usart.c
SRCS += bootloader_test/timing/timing.c

CFLAGS += -Ibootloader_test/api/
CFLAGS += -Ibootloader_test/print/
CFLAGS += -Ibootloader_test/timing/
CFLAGS += -Ibootloader_test/drivers/
CFLAGS += -Ibootloader_test/tests/
CFLAGS += -Ibootloader_test/
