# This application use HAL for leds
HAL_LED=yes

# You can add more sources here if needed
SRCS +=
INCLUDES +=

# Define default network settings
CFLAGS += -DNETWORK_ADDRESS=$(default_network_address)
CFLAGS += -DNETWORK_CHANNEL=$(default_network_channel)
