# Use App Scheduler and configure it
APP_SCHEDULER=yes
APP_SCHEDULER_TASKS=4

CFLAGS += -DWITH_DIRECTED_ADVERTISER

CFLAGS += -DADVERTISER_RATE_SEC=$(default_advertiser_rate_s)
CFLAGS += -DQUEUING_TIME_MS=$(default_queuing_time_ms)



CFLAGS += -DSCAN_RAND_MS=$(default_scan_rand_ms)
CFLAGS += -DSEND_RAND_MS=$(default_send_rand_ms)