# You can add more sources here and libraries if needed
SRCS +=
INCLUDES +=
LIBS +=

# This application use HAL for buttons and leds
HAL_BUTTON=yes
HAL_LED=yes

# Example:
# SRCS += $(SRCS_PATH)my_driver.c
# include math.h lib
# LIBS += -lm

# Define default network settings
CFLAGS += -DNETWORK_ADDRESS=$(default_network_address)
CFLAGS += -DNETWORK_CHANNEL=$(default_network_channel)
