# You can add more sources here and libraries if needed
SRCS +=
INCLUDES +=
LIBS +=

# Example:
# SRCS += $(SRCS_PATH)my_driver.c
# include math.h lib
# LIBS += -lm

# Enable application debug prints
APP_PRINTING=yes

# Custom logs to have High precision time
CFLAGS += -DDEBUG_LOG_CUSTOM
CFLAGS += -DDEBUG_LOG_PRINT_MODULE_NAME
CFLAGS += -DDEBUG_LOG_PRINT_TIME_HP
CFLAGS += -DDEBUG_LOG_PRINT_LEVEL

# Enable software AES
SW_AES=yes