# You can add more sources here and libraries if needed
SRCS +=
INCLUDES +=
LIBS +=
LDFLAGS +=

# Example:
# SRCS += $(SRCS_PATH)my_driver.c
# LIBS += my_lib.a
# include math.h lib
# LDFLAGS += -lm

# Enable application debug prints
APP_PRINTING=yes

# Use Shared Data
SHARED_DATA=yes

# Generic util functions are needed (api.c)
include $(UTIL_PATH)makefile
