name: Build and deploy doc

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: wirepas/sdk-builder:latest
      options: --user 0

    steps:
    - uses: actions/checkout@v2
    - name: Generate doc
      # Build the doc always
      run: make doxygen
    - name: Deploy doc
      # Only push the doc when pushed to master
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
